# @package _global_

hydra:
  sweeper:
    params:
      target_generator.amount_reducer._target_: torch.sum
      target_transaction_count: "{lower: 90, upper: 110}"
      transaction_count_in_a_day: "{min: 1, max: 3}"
